### ISSUE TITLE
Mapping files for Cholesterol

### ISSUE THREAD

**Issue by jmelcr** [NMRLipids/NmrLipidsCholXray#10]
When calculating the scattering factors for mixed membranes (POPC/Chol), one gets errors like "couldn't find Cxx, Add it to the .dat file.". Looks like the Cholesterol atom-names are missing - or do we have the definitions somewhere?

**Comment by ohsOllila** [comment]
Currently there are separate mapping files for cholesterol. I am currently collecting the data in the [MATCH repository](https://github.com/NMRLipids/MATCH). The data in Data folder, mapping files in MAPPING folder. In README.md files in each data set are the commands that needs to be run before [makereport.sh](https://github.com/NMRLipids/MATCH/blob/master/scratch/report/makeREPORT.sh), for example see https://github.com/NMRLipids/MATCH/tree/master/Data/Lipid_Bilayers/POPC%2B50%25chol/T310K/MODEL_CHARMM36_GROMACS5.0

I have not had time to make a documentation about this yet, sorry about that. Hopefully this helps. Do not hesitate to ask further questions.

**Comment by ohsOllila** [comment]
This concerns the preliminary version of the databank which is outdated now. I will close this issue now.
