### ISSUE TITLE
Scaling experimental form factors in plot with multiple simulation results

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/NmrLipidsCholXray#18]
The y-axis scale of form factors cannot be explicitly measured in experiments. Therefore, the y-axis of the experimental form factor is typically scaled to match with simulations. This currently not done in figure 
https://github.com/NMRLipids/NmrLipidsCholXray/blob/master/FIGS/FormFactors-eps-converted-to.pdf
because we have several simulations which give inequal form factors. Therefore it is not clear against which simulation results we should scale the experimental results.

We have to figure out some reasonable solution. However, it may be a good idea to first finalize the details in the form factor calculation code and recalculate all the data with a proper form factor calculation code, see issues https://github.com/NMRLipids/MATCH/issues/50 and https://github.com/NMRLipids/MATCH/issues/56

**Comment by markussmiettinen** [comment]
As it seems that one can only reliably look at the relative heights of the lobes, one solution would be to fix, say, the height of the second lobe to be the same in all the data sets.

**Comment by ohsOllila** [comment]
In experiments, one can only look at the relative heights. However, when comparing between simulations, the heights could be compared. If we scale different simulations to the same height we will underestimate the differences between force fields. 

Other options could be to select one simulation and scale experiment based on that (however, this would make one simulation to look unfairly better), or to scale based on average from simulations.

**Comment by markussmiettinen** [comment]
How about finding the simulation that best reproduces the zeros of the experimental curve, and scaling the experimental heights to that?

Or, if one rather uses averages, to weight the simulational curves used for the average by how well they reproduce the experimental zeros.

**Comment by ohsOllila** [comment]
This is now resolved in the databank using quality measure based on first minima (or zero) location, and in the NMRlipids III by looking interpolated data and minima (zeros). I will close this.
